# Лабораторная работа №1. Парсер сайта "Изба - читальня"

In [ ]:
import requests
from bs4 import BeautifulSoup
from random import randint

#### Черновик

In [ ]:
r = requests.get('https://www.chitalnya.ru/work/3610167/') # вернуть разметку страницу по ссылке
r.text

'<!DOCTYPE html>\n<html lang="ru">\n<head>\n<meta charset="utf-8">\n<title>Бизнес класс ~ Проза (Рассказ)</title><meta name="description" content="Проза (Рассказ). Название произведения: Бизнес класс. Автор: Александр Рыбак. Современный литературный сайт для поэтов, писателей, исполнителей музыки и песен." /><meta name="keywords" content="стихи, проза, стихотворения, любовная лирика, конкурсы, произведение, роман, публикация, поэт, прозаик, новелла, миниатюра, автор, литература, творчество, лирика, поэзия, рецензия, критик, рассказ, повесть" />\n<meta property="og:url" content="https://www.chitalnya.ru/work/3610167/" />\n<meta property="og:image" content="https://www.chitalnya.ru/images/logo2020.png" />\n<meta property="vk:image" content="https://www.chitalnya.ru/images/logo2020.png" />\n<base href="https://www.chitalnya.ru/"/>\n<link href="https://cdn.adfinity.pro/foralls/adfinity_1.1.css" rel="stylesheet">\n<script src="https://yandex.ru/ads/system/header-bidding.js"></script>\n<scri

In [ ]:
type(r.text)

str

In [ ]:
soup = BeautifulSoup(r.text) # пред. обработка через BeautifulSoup
soup

In [ ]:
type(soup)

bs4.BeautifulSoup

In [ ]:
div=soup.find_all('div', {'class': 'col-md-9 x2'}) # взять данные из поля
text = div[0].text

In [ ]:
print(text)

In [ ]:
len(div)

1

In [ ]:
type(text)

str

In [ ]:

a = randint(3500000,3650000)

In [ ]:
a

3604548

In [ ]:
url = 'https://www.chitalnya.ru/work/' + str(a) +'/'
url

'https://www.chitalnya.ru/work/3604548/'

In [ ]:
r = requests.get(url) # вернуть разметку страницу по ссылке
r.text

'<!DOCTYPE html>\n<html lang="ru">\n<head>\n<meta charset="utf-8">\n<title>Стихи, проза, стихи о любви и многое другое на литпортале Изба-Читальня</title>\n<meta name="keywords" content="стихи, проза, стихотворения, любовная лирика, конкурсы, произведение, роман, публикация, поэт, прозаик, новелла, миниатюра, автор, литература, творчество, лирика, поэзия, рецензия, критик, рассказ, повесть" />\n<meta property="og:url" content="https://www.chitalnya.ru/error.php" />\n<meta property="og:image" content="https://www.chitalnya.ru/images/logo2020.png" />\n<meta property="vk:image" content="https://www.chitalnya.ru/images/logo2020.png" />\n<base href="https://www.chitalnya.ru/"/>\n<!--[if lt IE 9]>\n    <script src="/libs/html5shiv/es5-shim.min.js"></script>\n    <script src="/libs/html5shiv/html5shiv.min.js"></script>\n    <script src="/libs/html5shiv/html5shiv-printshiv.min.js"></script>\n    <script src="/libs/respond/respond.min.js"></script>    \n    <link rel="stylesheet" type="text/css

In [ ]:
soup = BeautifulSoup(r.text)

In [ ]:
div=soup.find_all('div', {'class': 'col-md-9 x2'}) # взять данные из поля
# div
text = div[0].text
text

'\n\xad\xadГей, славяне!Егорий!Серпантином  дудочки  звук ,травы невинны,-соком, соками,зачатие  Божьей  Матери!Воздух дымкой  стелитьсяв потаенных  закромах  души,тревожа  первоначальный  образ.Начало  пасьбы,вербными,  на  поле,веточками ,освященными  ,скот выгоняют,пиво  ручьями,пироги, яичницу-пастухам,первая  кружка за ГеоргияХраброго,победителя басурман.Открываются  ворота торговли,срок сделкам  и наймам.-Налетай  народ! Продаю!Меняю! Меняю!Продаю!Сегодня  вельми помогаетроса,коли  телешком покататься ,нагим  искупаться.-Не  бранись  на  Егория- молния  убьет,-наставляют бабушки внучат.Народ  ублажаетГеоргия Победоносца,почитаемого в земле Русскойсвятого и крестится, глядяна  небо  !\n\n'

In [ ]:
print(text)

In [ ]:
len(div)

1

In [ ]:
# Открываем файл в режиме записи
with open("text_data.txt", "w") as file:
    # Записываем текст в файл
    file.write(text)
# Файл автоматически закрывается после выхода из блока with

#### Парсинг

In [ ]:
# Открываем файл в режиме записи
with open("text_data.txt", "w") as file:
  i = 0
  while i != 1000:
    number = randint(3500000,3650000)
    url = 'https://www.chitalnya.ru/work/' + str(number) +'/'
    r = requests.get(url) # вернуть разметку страницу по ссылке

    soup = BeautifulSoup(r.text) # пред. обработка через BeautifulSoup
    div=soup.find_all('div', {'class': 'col-md-9 x2'}) # взять данные из поля

    try:
      text = div[0].text
    except IndexError:
        continue

    # Записываем текст в файл
    file.write(text + '\n')
    i += 1

    if i % 20 == 0:
      print(f'Стихов записано в файл:{i}')
# Файл автоматически закрывается после выхода из блока with

Стихов записано в файл:20
Стихов записано в файл:40
Стихов записано в файл:60
Стихов записано в файл:80
Стихов записано в файл:100
Стихов записано в файл:120
Стихов записано в файл:140
Стихов записано в файл:160
Стихов записано в файл:180
Стихов записано в файл:200
Стихов записано в файл:220
Стихов записано в файл:240
Стихов записано в файл:260
Стихов записано в файл:280
Стихов записано в файл:300
Стихов записано в файл:320
Стихов записано в файл:340
Стихов записано в файл:360
Стихов записано в файл:380
Стихов записано в файл:400
Стихов записано в файл:420
Стихов записано в файл:440
Стихов записано в файл:460
Стихов записано в файл:480
Стихов записано в файл:500
Стихов записано в файл:520
Стихов записано в файл:540
Стихов записано в файл:560
Стихов записано в файл:580
Стихов записано в файл:600
Стихов записано в файл:620
Стихов записано в файл:640
Стихов записано в файл:660
Стихов записано в файл:680
Стихов записано в файл:700
Стихов записано в файл:720
Стихов записано в файл:740
Стихо

# Лабораторная работа №2. Предварительная обработка текста

#### Загрузка выборки на английском языке (примеры на основе coco_image_captions)

In [ ]:
START_LETTER = 0 # номер начального слова (слово с которого начинаются все тексты, которое подается первым на нейронную сеть, чтобы указать начало предложения)
MAX_SEQ_LEN = 20 # максимальная длина примеров
VOCAB_SIZE = 4838 # размер словаря слов
CLOSING_WORD = 1814 # слово конца предложения / слово заполнитель (вставляется в конец текста для заполнения текста до заданной длины)

# (правда START_LETTER для английской не совпадает, поздно заметил)

In [ ]:
# загрузка словаря
import numpy as np
import pickle

vocab_file_path = '/content/drive/MyDrive/Набор данных/coco_image_captions/coco_image_captions_vocab_cotra_test.pkl'

word, vocab = pickle.load(open(vocab_file_path, 'rb')) # загручаем данные из файла, используя модуль pickle;   rb (read binary) - в файле находятся бинарные данные

In [ ]:
word

In [ ]:
vocab

In [ ]:
print('Пример первого слова из словаря:', word[0])
print('Пример слова заполнителя (пробел):', word[1814])
word[1814]

Пример первого слова из словаря: raining
Пример слова заполнителя (пробел):  


' '

In [ ]:
# загрузка обучающей выборки
train_file_path = '/content/drive/MyDrive/Набор данных/coco_image_captions/coco_image_captions_train.txt'
f = open(train_file_path, 'r')
data_file_train = []
for line in f:
  line = line.replace('\n', '')
  line = line.split()
  for i in range(len(line)):
    line[i] = int(line[i])
  data_file_train.append(line)
data_file_train = np.array(data_file_train)[:, :MAX_SEQ_LEN]
print("Примеров в обучающей выборке: ", len(data_file_train))

Примеров в обучающей выборке:  80000


In [ ]:
# загрузка тестовой выборки
test_file = '/content/drive/MyDrive/Набор данных/coco_image_captions/coco_image_captions_test.txt'
f = open(test_file, 'r')
data_file_test = []
for line in f:
  line = line.replace('\n', '')
  line = line.split()
  for i in range(len(line)):
    line[i] = int(line[i])
  data_file_test.append(line)
data_file_test = np.array(data_file_test)[:, :MAX_SEQ_LEN]
print("Примеров в тестовой выборке: ", len(data_file_test))

Примеров в тестовой выборке:  5000


In [ ]:
# примеры из обучающей выборки
print("Примеры из обучающей выборки")
batch_size = 50 # количество случайных примеров для вывода примеров

samples = data_file_train[np.random.randint(0, len(data_file_train), batch_size)]
output_function = []
for samp in samples:
  line = [word[x] for x in samp]
  line = ' '.join(line)
  output_function.append(line)

for i, output in enumerate(output_function):
  print("#", i, "\tПример: ", output)

Примеры из обучающей выборки
# 0 	Пример:  A lady flying a kite with a black dog nearby .                  
# 1 	Пример:  A small family sitting on a bench on a grassy field surrounded by ducks .          
# 2 	Пример:  Truck with off road vehicle in bed in front of trailer in driveway .            
# 3 	Пример:  Several ducks standing in the grass next to a river .                  
# 4 	Пример:  A cat that is curled up and laying on a bed .                
# 5 	Пример:  A black and white photo of a young man doing a trick on a skateboard .        
# 6 	Пример:  A very small girl flying a kite in a field .                  
# 7 	Пример:  A couple of people that are sitting down on a table .                
# 8 	Пример:  A person wearing a hat and glasses with a refrigerator behind them .              
# 9 	Пример:  A young boy holding a donut with pink sprinkles on it .                
# 10 	Пример:  A person that is riding on a brown colored horse , in a grass field with tall trees i

#### Загрузка выборки на русском языке

In [207]:
START_LETTER = 4999 # номер начального слова (слово с которого начинаются все тексты, которое подается первым на нейронную сеть, чтобы указать начало предложения)
MAX_SEQ_LEN = 10 # максимальная длина примеров
VOCAB_SIZE = 5000 # размер словаря слов
CLOSING_WORD = 4997 # слово конца предложения / слово заполнитель (вставляется в конец текста для заполнения текста до заданной длины)

In [208]:
# загрузка словаря
import numpy as np
import pickle

vocab_file_path = '/content/drive/MyDrive/Набор данных/stihi_ru/stihi_ru_vocab.pkl'
word, vocab = pickle.load(open(vocab_file_path, 'rb'))

In [209]:
print('Пример первого слова из словаря:', word[0])
print('Пример стартового слова (_START_):', word[4999])
print('Пример слова заполнителя (пробел):', word[4997])
word[4997]

Пример первого слова из словаря: и
Пример стартового слова (_START_): _START_
Пример слова заполнителя (пробел): 


''

In [160]:
len(word)

5000

In [49]:
print(word)

['и', 'в', 'не', 'я', 'на', 'что', 'с', 'как', 'ты', 'а', 'но', 'мне', 'то', 'все', 'за', 'мы', 'так', 'по', 'от', 'к', 'он', 'это', 'тебя', 'меня', 'всё', 'у', 'о', 'из', 'же', 'когда', 'только', 'лишь', 'кто', 'где', 'нет', 'для', 'бы', 'тебе', 'без', 'его', 'до', 'нам', 'жизнь', 'она', 'нас', 'ведь', 'вот', 'жизни', 'ни', 'их', 'быть', 'уже', 'если', 'чтоб', 'любовь', 'есть', 'да', 'будет', 'пусть', 'под', 'может', 'мой', 'там', 'сердце', 'был', 'было', 'они', 'себя', 'любви', 'во', 'вы', 'просто', 'всегда', 'тобой', 'мир', 'чтобы', 'всех', 'время', 'со', 'день', 'даже', 'или', 'теперь', 'ну', 'здесь', 'моя', 'снова', 'очень', 'её', 'себе', 'больше', 'хочу', 'надо', 'вновь', 'чем', 'жить', 'ли', 'тот', 'этот', 'глаза', 'души', 'ещё', 'свой', 'душа', 'много', 'каждый', 'раз', 'словно', 'знаю', 'вдруг', 'друг', 'всем', 'этом', 'уж', 'свет', 'вам', 'вас', 'них', 'твой', 'хоть', 'над', 'будто', 'люди', 'свою', 'ней', 'люблю', 'душе', 'им', 'счастье', 'была', 'своей', 'ей', 'буду', 'давн

In [50]:
print(vocab)

{'и': 0, 'в': 1, 'не': 2, 'я': 3, 'на': 4, 'что': 5, 'с': 6, 'как': 7, 'ты': 8, 'а': 9, 'но': 10, 'мне': 11, 'то': 12, 'все': 13, 'за': 14, 'мы': 15, 'так': 16, 'по': 17, 'от': 18, 'к': 19, 'он': 20, 'это': 21, 'тебя': 22, 'меня': 23, 'всё': 24, 'у': 25, 'о': 26, 'из': 27, 'же': 28, 'когда': 29, 'только': 30, 'лишь': 31, 'кто': 32, 'где': 33, 'нет': 34, 'для': 35, 'бы': 36, 'тебе': 37, 'без': 38, 'его': 39, 'до': 40, 'нам': 41, 'жизнь': 42, 'она': 43, 'нас': 44, 'ведь': 45, 'вот': 46, 'жизни': 47, 'ни': 48, 'их': 49, 'быть': 50, 'уже': 51, 'если': 52, 'чтоб': 53, 'любовь': 54, 'есть': 55, 'да': 56, 'будет': 57, 'пусть': 58, 'под': 59, 'может': 60, 'мой': 61, 'там': 62, 'сердце': 63, 'был': 64, 'было': 65, 'они': 66, 'себя': 67, 'любви': 68, 'во': 69, 'вы': 70, 'просто': 71, 'всегда': 72, 'тобой': 73, 'мир': 74, 'чтобы': 75, 'всех': 76, 'время': 77, 'со': 78, 'день': 79, 'даже': 80, 'или': 81, 'теперь': 82, 'ну': 83, 'здесь': 84, 'моя': 85, 'снова': 86, 'очень': 87, 'её': 88, 'себе': 89

In [210]:
def make_reverse_vocab(vocab):
  reverse_vocab = {value: key for key, value in vocab.items()}
  return reverse_vocab
reverse_vocab = make_reverse_vocab(vocab)
# reverse_vocab

In [211]:
# загрузка обучающей выборки
train_file_path = '/content/drive/MyDrive/Набор данных/stihi_ru/stihi_ru_realtrain.txt'
f = open(train_file_path, 'r')

data_file_train = []
for line in f:
  line = line.replace('\n', '') # удаляем перевод строки, делаем всё содержимое одной строкой
  line = line.split()           # разделяет текущую строку на предложения, разделить - ''
  for i in range(len(line)):    # для каждого индекса слова в предложении
    line[i] = int(line[i])      # переводим индекс в int вместо str
  data_file_train.append(line)  # добавляем в список индексов слов
# data_file_train - numpy-массив из списков индексов (предложений), каждый список имеет длину 10 индексов
# data_file_train = np.array(data_file_train)[:, :MAX_SEQ_LEN]  #
print("Примеров в обучающей выборке: ", len(data_file_train))

Примеров в обучающей выборке:  400000


In [6]:
for sentence in data_file_train[:10]:
  print(sentence)

[34, 4209, 48, 19, 520, 0, 1773, 4997, 4997, 4997]
[3, 874, 62, 4, 3738, 0, 2076, 4997, 4997, 4997]
[83, 1514, 61, 312, 548, 4997, 4997, 4997, 4997, 4997]
[55, 2305, 41, 191, 3117, 4997, 4997, 4997, 4997, 4997]
[326, 18, 422, 15, 115, 3297, 4997, 4997, 4997, 4997]
[32, 1, 903, 44, 1, 4021, 1054, 1486, 4997, 4997]
[19, 1800, 4, 4570, 2583, 4997, 4997, 4997, 4997, 4997]
[468, 490, 36, 186, 1077, 263, 3370, 4997, 4997, 4997]
[8, 2251, 0, 181, 635, 452, 4997, 4997, 4997, 4997]
[46, 30, 4263, 19, 2911, 4997, 4997, 4997, 4997, 4997]


##### тестовая выборка

In [7]:
# загрузка тестовой выборки
test_file_path = '/content/drive/MyDrive/Набор данных/stihi_ru/stihi_ru_realtest.txt'
f = open(test_file_path, 'r')
data_file_test = []
for line in f:
  line = line.replace('\n', '')
  line = line.split()
  for i in range(len(line)):
    line[i] = int(line[i])
  data_file_test.append(line)
data_file_test = np.array(data_file_test)[:, :MAX_SEQ_LEN]
print("Примеров в тестовой выборке: ", len(data_file_test))

Примеров в тестовой выборке:  5000


In [8]:
data_file_test[0]

array([ 156,  247,    0,   85,   54, 4997, 4997, 4997, 4997, 4997])

In [9]:
# примеры из обучающей выборки
print("Примеры из обучающей выборки")
batch_size = 50 # количество случайных примеров для вывода примеров

samples = data_file_train[np.random.randint(0, len(data_file_train), batch_size)] #  код случайным образом выбирает элементы из массива data_file_train с использованием случайных индексов
output_function = []
for samp in samples:
  line = [word[x] for x in samp]
  line = ' '.join(line)
  output_function.append(line)

for i, output in enumerate(output_function):
  print("#", i, "\tПример: ", output)

Примеры из обучающей выборки


TypeError: ignored

#### Загрузка собственных текстовых данных (спарсил в первой лабе)

In [ ]:
test_file_path = '/content/drive/MyDrive/Набор данных/text_data.txt'

with open(test_file_path,'r') as text_file:
  original_text = text_file.read()

#### Черновик

##### 1 шаг

In [ ]:
type(original_text)

str

In [ ]:
print(original_text[:4000])

In [ ]:
original_text = original_text.replace('\n', ' ')   # делаем весь текст в одну строку

In [ ]:
print(original_text[:4000])

 ­­­­­­"Анна Павлова в Сильфиде" - эскиз художника Валентина Серова к основной афише для театра С. Дягилева "Русские сезоны" в Париже 1909 г.***повсюду тысячи афиш...и город наэлектризован,ведь вскоре "Русские сезоны"прибудут удивлять Париж!...в наследие на много летСеров донёс углём и меломдвижений слаженно-умелыхполётность, невесомость... светпрекрасной Анны! кто бы знал,однажды хрупкая тростинкавзойдёт на сцену Мариинки,и станет явь волшебней сна!её точёный силуэт,изгибы, флёр тончайших кружевмогли в момент обезоружитьи тех, кому был чужд балет.она любила в танце житьталантливо и филигранно,стихия Анны - грусть, не драма,земная лирика души.известный в мире педагог*когда-то искренне заметил:"она пушинка или ветер,изящный, трепетный цветок..."неподражаемо-легка,икона русского балетазатронула сердца по свету,чтоб в них остаться на века...❈～❈～❈～❈～❈2023* балетмейстер Мариус Петипа    ­То, как ты думаешь о Богечто ожидаешь в жизни тыкак Он с тобой общаться можеткак ждёшь что Он направит ж

In [ ]:
original_text = original_text.lower() # переводим все символы в нижний регистр

In [ ]:
print(original_text[:4000])

 ­­­­­­"анна павлова в сильфиде" - эскиз художника валентина серова к основной афише для театра с. дягилева "русские сезоны" в париже 1909 г.***повсюду тысячи афиш...и город наэлектризован,ведь вскоре "русские сезоны"прибудут удивлять париж!...в наследие на много летсеров донёс углём и меломдвижений слаженно-умелыхполётность, невесомость... светпрекрасной анны! кто бы знал,однажды хрупкая тростинкавзойдёт на сцену мариинки,и станет явь волшебней сна!её точёный силуэт,изгибы, флёр тончайших кружевмогли в момент обезоружитьи тех, кому был чужд балет.она любила в танце житьталантливо и филигранно,стихия анны - грусть, не драма,земная лирика души.известный в мире педагог*когда-то искренне заметил:"она пушинка или ветер,изящный, трепетный цветок..."неподражаемо-легка,икона русского балетазатронула сердца по свету,чтоб в них остаться на века...❈～❈～❈～❈～❈2023* балетмейстер мариус петипа    ­то, как ты думаешь о богечто ожидаешь в жизни тыкак он с тобой общаться можеткак ждёшь что он направит ж

In [ ]:
print(original_text[:4000])

 ­­­­­­"анна павлова в сильфиде" - эскиз художника валентина серова к основной афише для театра с. дягилева "русские сезоны" в париже 1909 г.***повсюду тысячи афиш...и город наэлектризован,ведь вскоре "русские сезоны"прибудут удивлять париж!...в наследие на много летсеров донёс углём и меломдвижений слаженно-умелыхполётность, невесомость... светпрекрасной анны! кто бы знал,однажды хрупкая тростинкавзойдёт на сцену мариинки,и станет явь волшебней сна!её точёный силуэт,изгибы, флёр тончайших кружевмогли в момент обезоружитьи тех, кому был чужд балет.она любила в танце житьталантливо и филигранно,стихия анны - грусть, не драма,земная лирика души.известный в мире педагог*когда-то искренне заметил:"она пушинка или ветер,изящный, трепетный цветок..."неподражаемо-легка,икона русского балетазатронула сердца по свету,чтоб в них остаться на века...❈～❈～❈～❈～❈2023* балетмейстер мариус петипа    ­то, как ты думаешь о богечто ожидаешь в жизни тыкак он с тобой общаться можеткак ждёшь что он направит ж

##### 2 шаг

In [ ]:
# подключение библиотеки
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
tokenized_text = nltk.word_tokenize(original_text) # переводим весь текст в список слов (токенизируем)
tokenized_text

In [ ]:
from collections import Counter
cntr = Counter(tokenized_text) # считаем количество упоминаний каждого слова
cntr

In [ ]:
most_words = list(cntr.most_common(5000-3)) # наиболее частые N-3 слов (добавится заполнитель и два зарезервированных слова)
most_words

In [ ]:
len(most_words)

4997

In [ ]:
most_words[:10]

[(',', 38251),
 ('.', 16499),
 ('и', 11859),
 ('в', 8714),
 ('не', 6221),
 ('на', 4763),
 ('!', 3638),
 ('я', 3427),
 ('что', 3360),
 ('с', 3273)]

In [ ]:
# создание словаря слов: каждому слову присваиваем индекс, в зависимости от количества его упоминаний в текстовых данных
vocab = dict()
for i in range(len(most_words)):
  vocab[most_words[i][0]] = i

In [ ]:
# добавление специальных слов в словарь
vocab[' ']=len(vocab) # добавить пробел (заполнитель)
vocab['_UNK_']=len(vocab) # добавить удаленное слово (удаляемые слова заменяются этим словом)
vocab['_START_']=len(vocab) # добавить стартовое слово в словарь

In [ ]:
vocab[' ']

4997

In [ ]:
def get_key_by_value(dictionary, value):
    for key, val in dictionary.items():
        if val == value:
            return key
    return None

In [ ]:
key = get_key_by_value(vocab,4997)
key

' '

##### 3 шаг

In [ ]:
import re

def split_sentences(text):
  sentences = re.split(r'(?<=[.!?…])\s+', text)
  return sentences

In [ ]:
print(original_text[:4000])

 ­­­­­­"анна павлова в сильфиде" - эскиз художника валентина серова к основной афише для театра с. дягилева "русские сезоны" в париже 1909 г.***повсюду тысячи афиш...и город наэлектризован,ведь вскоре "русские сезоны"прибудут удивлять париж!...в наследие на много летсеров донёс углём и меломдвижений слаженно-умелыхполётность, невесомость... светпрекрасной анны! кто бы знал,однажды хрупкая тростинкавзойдёт на сцену мариинки,и станет явь волшебней сна!её точёный силуэт,изгибы, флёр тончайших кружевмогли в момент обезоружитьи тех, кому был чужд балет.она любила в танце житьталантливо и филигранно,стихия анны - грусть, не драма,земная лирика души.известный в мире педагог*когда-то искренне заметил:"она пушинка или ветер,изящный, трепетный цветок..."неподражаемо-легка,икона русского балетазатронула сердца по свету,чтоб в них остаться на века...❈～❈～❈～❈～❈2023* балетмейстер мариус петипа    ­то, как ты думаешь о богечто ожидаешь в жизни тыкак он с тобой общаться можеткак ждёшь что он направит ж

In [ ]:
sentences = split_sentences(original_text)

In [ ]:
type(sentences)

list

In [ ]:
len(sentences)

21933

In [ ]:
sentences[49]

'молодое «митинговое мясо» пошло в «расходные материалы» для террористической деятельности.'

In [ ]:
nltk.word_tokenize(sentences[49])

['молодое',
 '«',
 'митинговое',
 'мясо',
 '»',
 'пошло',
 'в',
 '«',
 'расходные',
 'материалы',
 '»',
 'для',
 'террористической',
 'деятельности',
 '.']

In [ ]:
set(nltk.word_tokenize(sentences[49]))

{'.',
 '«',
 '»',
 'в',
 'деятельности',
 'для',
 'материалы',
 'митинговое',
 'молодое',
 'мясо',
 'пошло',
 'расходные',
 'террористической'}

In [ ]:
# for word in set(nltk.word_tokenize(sentences[49])):
#   print(word)

In [ ]:
set_of_vocab_words = set(vocab.keys())
sentence_to_del = []

for sentence in sentences:
  # print(i, sentence)
  words_in_sentence = set(nltk.word_tokenize(sentence))  # разбиваем каждое предложение на слова
  for word in words_in_sentence:
    # print(word)
    if word not in set_of_vocab_words:
      sentence_to_del.append(sentence)    # сохраняем индексы предложений, где есть слова, которые не входят в словарь
      break

  if (len(words_in_sentence) < 5) or len(words_in_sentence) > 15:
    sentence_to_del.append(sentence)    # сохраняем индексы предложений, в которых меньше 5 или больше 15 слов

In [ ]:
sentence_to_del = set(sentence_to_del)

In [ ]:
len(sentence_to_del)

19411

In [ ]:
sentenses = list(set(sentences) - sentence_to_del)   # убираем из множества сообщений те, которые не подходят

In [ ]:
type(sentenses)

list

In [ ]:
len(sentenses)

1823

In [ ]:
sentenses[:10]

['но - вряд ли опасно для врага.',
 'тишина и наши эмоции.',
 'но он не отвечал.',
 'здесь он может петь от души.',
 '– он помогает ему подняться.',
 'такой вертолет я видел в первый раз.',
 '– а что это?',
 'и тогда закричал я.',
 'и это далеко не пригожин.',
 'а потом подумал и попросил помощи и у гуаньинь.']

In [ ]:
sentenses[0]

'но - вряд ли опасно для врага.'

In [ ]:
standard_sentenses = []
for sentence in sentenses:
  words_in_sentence = nltk.word_tokenize(sentence)  # разбиваем каждое предложение на слова
  num_words = len(words_in_sentence)
  print(num_words)
  # print(type(sentence))
  if num_words != 15:
    num_spaces = 15 - num_words
    # sentence +=  num_spaces * ' '
    for _ in range(num_spaces):
      words_in_sentence.append(' ')

    sentence = ' '.join(words_in_sentence)

    standard_sentenses.append(sentence)
    print(sentence)
    print(len(words_in_sentence))
  else:
    standard_sentenses.append(sentence)
    print(sentence)

In [ ]:
standard_sentenses[0]

'но - вряд ли опасно для врага .              '

In [ ]:
words_in_sentence = nltk.word_tokenize(standard_sentenses[0])
print(len(words_in_sentence))
print(words_in_sentence)

8
['но', '-', 'вряд', 'ли', 'опасно', 'для', 'врага', '.']


In [ ]:
words_in_sentence = standard_sentenses[0].split()
len(words_in_sentence)

8

##### 4 шаг

In [ ]:
replaced_sentences = []
for sentence in standard_sentenses:
  words_in_sentence = nltk.word_tokenize(sentence)
  replaced_sentence = []

  for word in words_in_sentence:
    if word in vocab:
      index = vocab[word]
      replaced_sentence.append(str(index))
    else:
      replaced_sentence.append(word)

  replaced_sentences.append(' '.join(replaced_sentence))

In [ ]:
replaced_sentences[:1]

['20 10 868 98 3720 48 1836 1']

In [ ]:
replaced_sentences[:2]

['20 10 868 98 3720 48 1836 1', '883 2 293 2358 1']

In [ ]:
replaced_sentences = ' '.join(replaced_sentences)

In [ ]:
type(replaced_sentences)

str

##### 5 шаг

In [ ]:
processed_text_path = '/content/processed_text.txt'

with open(processed_text_path,'w') as text_file:
  text_file.write(replaced_sentences)

In [ ]:
print(type(vocab))

<class 'dict'>


In [ ]:
import json
processed_vocab_path = '/content/processed_vocab.txt'

vocab = json.dumps(vocab)

with open(processed_vocab_path,'w') as text_file:
  text_file.write(vocab)

#### Обработка текста

In [ ]:
# подключение библиотеки
import nltk
nltk.download('punkt')
from collections import Counter
import re

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
class Preprocessing():
  # делаем весь текст в одну строку
  def one_line(text):
    return text.replace('\n', ' ')  # делаем весь текст в одну строку

  # переводим все символы в нижний регистр
  def to_lower(text):
    return text.lower()             # переводим все символы в нижний регистр

  # токенизируем текст
  def tokenize_text(text):
    return nltk.word_tokenize(text) # переводим весь текст в список слов (токенизируем)

  # список наиболее часто упоминаемых слов
  def most_words(text):
    tokenized_text = Preprocessing.tokenize_text(text)
    cntr = Counter(tokenized_text) # считаем количество упоминаний каждого слова
    return list(cntr.most_common(5000-3)) # наиболее частые N-3 слов (добавится заполнитель и два зарезервированных слова)

  # создаем словарь слов
  def make_vocab(text):
    text = Preprocessing.one_line(text)
    text = Preprocessing.to_lower(text)
    # создание словаря слов: каждому слову присваиваем индекс, в зависимости от количества его упоминаний в текстовых данных
    vocab = dict()
    most_words_list = Preprocessing.most_words(text)
    for i in range(len(most_words_list)):
      vocab[most_words_list[i][0]] = i

    # добавление специальных слов в словарь
    vocab[' ']=len(vocab) # добавить пробел (заполнитель)
    vocab['_UNK_']=len(vocab) # добавить удаленное слово (удаляемые слова заменяются этим словом)
    vocab['_START_']=len(vocab) # добавить стартовое слово в словарь
    return vocab

  # создаем обратный словарь слов
  def make_reverse_vocab(text):
    vocab = Preprocessing.make_vocab(text)   # создаем обычный словарь
    reverse_vocab = {value: key for key, value in vocab.items()}
    return reverse_vocab

  # разделяем текст на предложения по точке, воскл. и вопросит. знаку и многоточию
  def split_sentences(text):
    text = Preprocessing.one_line(text)
    text = Preprocessing.to_lower(text)
    sentences = re.split(r'(?<=[.!?…])\s+', text)
    return sentences

  # убираем лишние примеры предложений
  def examples_filtering(text):
    sentences = Preprocessing.split_sentences(text)
    vocab = Preprocessing.make_vocab(text)

    set_of_vocab_words = set(vocab.keys())
    sentence_to_del = []

    for sentence in sentences:
      words_in_sentence = set(nltk.word_tokenize(sentence))  # разбиваем каждое предложение на слова
      for word in words_in_sentence:
        if word not in set_of_vocab_words:
          sentence_to_del.append(sentence)    # сохраняем индексы предложений, где есть слова, которые не входят в словарь
          break

      if (len(words_in_sentence) < 5) or len(words_in_sentence) > 10:
        sentence_to_del.append(sentence)    # сохраняем индексы предложений, в которых меньше 5 или больше 10 слов

    sentence_to_del = set(sentence_to_del)
    sentenses = list(set(sentences) - sentence_to_del)   # убираем из множества сообщений те, которые не подходят
    return sentenses

  # заменяем текст индексами слов и дополняем каждый пример пробелами до 10 слов
  def examples_repalce(text):

    vocab = Preprocessing.make_vocab(text)

    sentenses = Preprocessing.examples_filtering(text)

    replaced_sentences = []

    for sentence in sentenses:
      words_in_sentence = Preprocessing.tokenize_text(sentence)
      num_words = len(words_in_sentence)
      replaced_sentence = []

      for word in words_in_sentence:   # заменяем слова числами
        if word in vocab:
          index = vocab[word]
          replaced_sentence.append(str(index))
        else:
          replaced_sentence.append(word)

      if num_words != 10:             # добавляем нужное количество пробелов
        num_spaces = 10 - num_words

        for _ in range(num_spaces):
          replaced_sentence.append(str(vocab[' ']))


      replaced_sentences.append(' '.join(replaced_sentence))
    return '\n'.join(replaced_sentences)


In [ ]:
print(original_text[:4000])

In [ ]:
reverse_vocab = Preprocessing.make_reverse_vocab(original_text)
reverse_vocab

In [ ]:
examples = Preprocessing.examples_filtering(original_text)
examples

In [ ]:
print(len(examples))

1519


In [ ]:
processed_text = Preprocessing.examples_repalce(original_text)

In [ ]:
print(processed_text[:37])

255 0 17 38 997 1 4997 4997 4997 4997


In [ ]:
processed_text_path = '/content/processed_text.txt'

with open(processed_text_path,'w') as text_file:
  text_file.write(processed_text)

In [ ]:
import json
processed_vocab_path = '/content/processed_vocab.txt'

vocab = json.dumps(vocab)

with open(processed_vocab_path,'w') as text_file:
  text_file.write(vocab)

# Лабораторная работа №3. Генерация текста

In [163]:
import torch
import torch.nn as nn

# подключение библиотеки
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [212]:
# Добавляем индекс слова __ START__ в начало каждого предложения выборки
for sentence in data_file_train:
  sentence.insert(0, 4999)   # вставляем в начало каждого предложения индекс слова __START__ :4999

In [213]:
data_file_train[:10]

[[4999, 34, 4209, 48, 19, 520, 0, 1773, 4997, 4997, 4997],
 [4999, 3, 874, 62, 4, 3738, 0, 2076, 4997, 4997, 4997],
 [4999, 83, 1514, 61, 312, 548, 4997, 4997, 4997, 4997, 4997],
 [4999, 55, 2305, 41, 191, 3117, 4997, 4997, 4997, 4997, 4997],
 [4999, 326, 18, 422, 15, 115, 3297, 4997, 4997, 4997, 4997],
 [4999, 32, 1, 903, 44, 1, 4021, 1054, 1486, 4997, 4997],
 [4999, 19, 1800, 4, 4570, 2583, 4997, 4997, 4997, 4997, 4997],
 [4999, 468, 490, 36, 186, 1077, 263, 3370, 4997, 4997, 4997],
 [4999, 8, 2251, 0, 181, 635, 452, 4997, 4997, 4997, 4997],
 [4999, 46, 30, 4263, 19, 2911, 4997, 4997, 4997, 4997, 4997]]

In [214]:
# data_file_train - numpy-массив из списков индексов (предложений), каждый список имеет длину 10 индексов
data_file_train = np.array(data_file_train)[:, :MAX_SEQ_LEN+1]
data_file_train[0]

array([4999,   34, 4209,   48,   19,  520,    0, 1773, 4997, 4997, 4997])

In [215]:
# ФОРМИРУЕМ ВХОДНУЮ ВЫБОРКУ ДАННЫХ
input_data = data_file_train[:,:-1]
input_data[0]

array([4999,   34, 4209,   48,   19,  520,    0, 1773, 4997, 4997])

In [216]:
# ФОРМИРУЕМ ВЫХОДНУЮ ВЫБОРКУ ДАННЫХ
target_data = data_file_train[:,1:]
target_data[0]

array([  34, 4209,   48,   19,  520,    0, 1773, 4997, 4997, 4997])

In [217]:
# ФОРМИРУЕМ ТЕНЗОРЫ
input_data = torch.LongTensor(input_data)
target_data = torch.LongTensor(target_data)

In [218]:
input_data[0]

tensor([4999,   34, 4209,   48,   19,  520,    0, 1773, 4997, 4997])

In [219]:
# Задать параметры для обучения
input_size = 100  # размерность входных данных, количество весов для каждого индекса слова
hidden_size = 100  # размер скрытого состояния LSTM
num_layers = 1  # количество слоев LSTM
# num_epochs = 10  # количество эпох обучения
learning_rate = 0.01  # скорость обучения
vocab_size = len(word) # 5000 слов в словаре

# Определить рекуррентную нейронную сеть LSTM
class LSTMModel(nn.Module):
  def __init__(self,input_size,hidden_size, vocab_size, num_layers = 1):
    super(LSTMModel, self).__init__()    # вызываем конструктор родительского класса nn.Module и инициализируем базовый функционал модуля

    self.embedding = nn.Embedding(vocab_size, input_size)   # аргумент 1 - размер словаря, аргумент 2 - размер вектора эмбеддинга
    self.lstm = nn.LSTM(input_size, hidden_size, num_layers)
    self.fc = nn.Linear(hidden_size, vocab_size)
    self.softmax = nn.LogSoftmax(dim = 1)

  def h_c_init(self, batch_size = 1):
    h0 = torch.zeros(batch_size,hidden_size).to(device)     # потом нужно учесть размер бачей (пока по умолчанию =1)
    c0 = torch.zeros(batch_size,hidden_size).to(device)
    return (h0,c0)


  # функция прямого прохода для 1 слова
  def forward(self,x, h,c):   # x - индекс слова; выбираем нужный эмбеддинг из таблицы
    # выбираем нужный эмбеддинг из таблицы
    embedded = self.embedding(x).unsqueeze(dim=0)  # метод .unsqueeze(dim = ) увеличивает размерность тензора на одно измерение в указанном измерении dim

    # ВХОДЫ
    # embedded - тензор, содержащий характеристики входной последовательности
    # h0 - тензор, содержащий начальное скрытое состояние для каждого элемента во входной последовательности
    # c0 - тензор, содержащий начальное состояние ячейки для каждого элемента во входной последовательности

    # ВЫХОДЫ
    # output - тензор, содержащий выходные объекты (h_t) из последнего слоя LSTM, для каждого t
    # hn - тензор, содержащий конечное скрытое состояние для каждого элемента в последовательности
    # cn - тензор, содержащий конечное состояние ячейки для каждого элемента в последовательности

    output, (hn, cn) = self.lstm(embedded, (h,c))
    output = self.fc(output)
    output = self.softmax(output)   #  dim 5000
    return output, hn, cn

  # функция генерации одного предложения (сэмпла)
  # start_index - индекс первого слова последовательности
  # max_seq_len - длина последовательности
  def sample(self, start_word = 4999, max_seq_len = 10):

    start_word = torch.tensor(start_word).to(device)  # делаем из целого числа тензор

    # Инициализируем тензор, в котором будут храниться последовательности
    sample = torch.zeros(1, max_seq_len).type(torch.LongTensor).to(device)

    h0 = self.h_c_init()[0]  # инициализируем скрытое состояние
    c0 = self.h_c_init()[1]  # инициализируем память ячеек

    h = h0
    c = c0

    for i in range(max_seq_len):
      out = self.forward(start_word, h, c)   # тензор с вероятностями следующего слова, скрытым состоянием и памятью ячеек

      h = out[1]
      c = out[2]

      # подаем на ВХОД тензор с вероятностью и количество индексов, которые нужно сгенерировать
      # на ВЫХОДЕ получаем сгененированный индекс токена (слова)
      out = torch.multinomial(torch.exp(out[0])**2, 1)         # **2

      # вставляем индекс в нужное место последовательности
      sample[:, i] = out.view(-1).data  # view(-1) преобразуем тензор в одномерную последовательность; data - свойство тензора, которое дает доступ к его данным
      start_word = out.view(-1).data[0]  # меняем стартовое слово на только что сгенерированное
    return sample

  def generate(self, sentence = None, reverse_vocab = reverse_vocab, vocab = vocab):
    if sentence == None:
      sentence_int = self.sample()[0]
      sentence_word = []
      for number in sentence_int:
        sentence_word.append(reverse_vocab[number.item()])

      print('Генерирую предложение полностью:', ' '.join(sentence_word))

    elif type(sentence) == str:      # проверяем, что введена строка
      sentence = sentence.lower()    # переводим в нижний регистр

      try:                         # пытаемся разбить входную последовательность на слова
        words_in_sentence = nltk.word_tokenize(sentence) # получаем список слов
      except Exception:            # если разбить не получается, то просто генерируем предложение с нуля
        sentence_int = self.sample()[0]
        sentence_word = []
        for number in sentence_int:
          sentence_word.append(reverse_vocab[number.item()])

        print('Генерирую предложение полностью:', ' '.join(sentence_word))

      else:                        # если получается разбить, то пытаемся сгенерировать оставшуюся часть предложения (чтобы длина была равна 10)
        if len(words_in_sentence) > 0 and len(words_in_sentence) < 10: # проверяем чтобы количество слов было в промежутке от 0 до 10 не включая
          num_words = 10 - len(words_in_sentence)   # вычисляем сколько слов надо сгенерировать
          start_word = words_in_sentence[-1]   # стартовое слово последовательности - последнее введеное слово
          try:
            start_word_index = vocab[start_word]      # пытаемся найти индекс слова из словаря
          except Exception:                           # если не находим - генерируем предложение с нуля полностью
            sentence_int = self.sample()[0]
            sentence_word = []
            for number in sentence_int:
              sentence_word.append(reverse_vocab[number.item()])

            print('Генерирую предложение полностью:', ' '.join(sentence_word))

          else:                  # если в словаре есть такое слово, то получаем его индекс и подаем его в функцию sample
            sentence_int = self.sample(start_word= start_word_index, max_seq_len = num_words)[0]
            sentence_word = []
            for number in sentence_int:
              sentence_word.append(reverse_vocab[number.item()])
            print('Генерирую оставшуюся часть предложения:',sentence + ' ' + ' '.join(sentence_word))

        else:
          print('Ошибка! Длина предложения должна быть в интервале от 0 до 10')
    else:
      print('Ошибка! Введите строку str')

In [220]:
def train(input_text,output_text, model, num_epochs = 1):

  # Определяем функцию потерь и оптимизатор
  criterion = nn.NLLLoss()
  optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

  # Обучаем модель
  for epoch in range(num_epochs):   # эпоха обучения

    for i, sentence in enumerate(input_text):   # перебираем предложения из выборки
      h = model.h_c_init()[0]         # инициализируем скрытое состояние
      c = model.h_c_init()[1]         # инициализируем память ячеек

      pred_sentence = []    # список, в котором будет содержаться 10 векторов размерностью 5000 (вероятности след. слова)

      for word in sentence:    # перебираем слова в предожении
        word = torch.tensor(word)  # переводим индекс слова в тензор

        # Проход вперед
        preds = model.forward(word, h, c)  # получаем тензор с вероятностями следующего слова, скрытым состоянием и памятью ячеек
        pred_word = preds[0]    # вектор с вероятностями
        h = preds[1]  # вектор скрытого состояния
        c = preds[2]  # вектор памяти ячеек
        pred_sentence.append(pred_word[0])   # добавляем вектор в список

      optimizer.zero_grad()   # обнуляем градиенты

      loss = 0
      for j, preds in enumerate(pred_sentence):     # считаем ошибку для каждого предложения
        loss += criterion(preds, output_text[i][j])   # суммируем ошибки каждого слова

      # Обратное распространение и оптимизация
      loss.backward()   # считаем веса
      optimizer.step()  # обновляем веса

      # # Вывести промежуточную информацию
      if i % 1000 == 0:
          print(i)
          print(loss)
          print(model.sample())

In [221]:
# Создаем модель и перевести данные на устройство (например, GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_data = input_data.to(device)
target_data = target_data.to(device)
model = LSTMModel(input_size, hidden_size, vocab_size).to(device)

In [320]:
model.generate('я пойду туда, где нас')

Генерирую оставшуюся часть предложения: я пойду туда, где нас ты и и в


In [330]:
model.generate()

Генерирую предложение полностью: ты как не меня не     


In [244]:
train(input_data,target_data,model)

<ipython-input-220-9ca5cb1f8609>:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  word = torch.tensor(word)  # переводим индекс слова в тензор


0
tensor(41.8559, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[  10,   13,    3,   22,    2,    6,   73, 4997, 4997, 4997]],
       device='cuda:0')
1000
tensor(32.7228, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[   0,    5,    3,    2,  715, 4997, 4997, 4997, 4997, 4997]],
       device='cuda:0')
2000
tensor(66.5246, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[   0,   19,  520,    5, 4997, 4997, 4997, 4997, 4997, 4997]],
       device='cuda:0')
3000
tensor(42.6769, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[   0,    2,   57,    1,   79, 4997, 4997, 4997, 4997, 4997]],
       device='cuda:0')
4000
tensor(40.2931, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[   3,  169,    3,    3,   10,  103,  104,   15, 4997, 4997]],
       device='cuda:0')
5000
tensor(54.6295, device='cuda:0', grad_fn=<AddBackward0>)
tensor([[  20,    8,  315, 4997, 4997, 4997, 4997, 4997, 4997, 4997]],
       device='cuda:0')
6000
tensor(36.8973, device='cuda:0', grad_fn=<AddBackward0>)

In [119]:
model.sample()

tensor([[ 766, 1389,  770, 4717, 3540,    5, 4717,  556, 4703,  798]],
       device='cuda:0')